# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Omar Montes Chavez's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Omar Montes Chavez 
headline: BS Mechanical Engineering
description: >- # dont remove this line. this will ignore all new lines until the next section
  Driven Mechanical Engineering student with hands‐on experience 
  in instrumentation, data acquisition, and motion control systems 
  for advanced scientific applications. During an internship at 
  SLAC National Accelerator Laboratory, analyzed cooling system 
  data for LCLS‐II superconducting cavities, streamlining procedures 
  with MATLAB scripting and Unix server interfaces. In an 
  undergraduate research role, developed computational tools 
  for hydrogen–natural gas blending and examined real‐gas 
  properties using Van der Waals and CoolProp models. Adept at 
  collaborating with cross‐functional teams, documenting complex 
  technical processes, and maintaining a culture of safety in 
  laboratory environments. 
# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/linkedinphoto.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1jHXOmWH_wiiM_YndjpYwAcLoQ8yMhxej/view?usp=sharing


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: omarmonteschavez/   # https://www.linkedin.com/in/{your url slug} 
  github:     # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Solidworks (3 Years)
    - SolidEdge (1 Year)
    - Siemens NX (1 Semester)
    - AutoCAD (1 Semester)
    - CATIA V5 (1 Semester)
    - Paraview (1 Semester) 
  - category: Prototyping
    tools:
    - CNC (1 Semester)
    - FDM (2 Years)
    - Arduino (3 Years) 
    - Raspberry Pi (1 Years)
    - Breadboarding for circuit testing (3 Years) 
  - category: Manufactioring/ Design / Best Practices
    tools:
    - GD&T ASME Y14.5M (2 Year)
    - ISO fits and tolerances (2 Years)
    - GCode (1 Semester)
    - TeamCenter PLM (2 Years) #Product LifeCycle Management 
    - INFOR Visual ERP (1 Year) #Enterprise Resource PLanning 
    - MySQL (1 Year) 
    - Ansys HFSS (1 Semester)
    - Ansys Fluent (1 Semester) 
    - Aerodynamic Simulation and Optimization (1.5 Years) 
    - LT Spice (3 Years) 
    - CoolProp (1 Semester) 
    - SU2 (1 Semester) 
    - GMSH (1 Semester) 
  - category: General Office 
    tools:
    - Microsoft Office (10 Years)
    - Outlook (8 Years) 
    - Microsoft Teams (6 Years)  
    - Overleaf/LateX (2 Years)
  - category: Programming Languages
    tools:
    - C++ (1 Year) 
    - Python (1 Semester) 
    - JavaScript (1 Semester) 
  - category: Problem Solving 
    tools:
    - Root Cause Analysis 
    - DFMEA / PFMEA 

Relevant Courses:
  - category: Undergraduate Level
    tools:
    - Fluids Dynamics
    - Numerical Methods and Analysis 
    - Thermodynamics
    - Materials and Material Processing 
    - CAD/CAM 
    - Powerplant System Design
    - Heat Transfer System Design 
    - Mechanical Control Systems 
    - Analytical Mechanics I/II 
    - Kinematics and Mechanics of Dynamic Systems 
    - Intro to Manufacturing Process
    - Modeling Analysis of Dynamic Systems 
    - Engineering Design 
  - category: Graduate Level 
    tools: 
    - Project Management 
    
# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   xnnjzlvv



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
